/*
 * Copyright (C) 2018 The ontology Authors
 * This file is part of The ontology library.
 *
 * The ontology is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The ontology is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with The ontology.  If not, see <http://www.gnu.org/licenses/>.
 */

package dht

import (
	"context"
	"time"

	"github.com/ontio/ontology/account"
	"github.com/ontio/ontology/common/log"
	kb "github.com/ontio/ontology/p2pserver/dht/kbucket"
	"github.com/ontio/ontology/p2pserver/dht/peer"
)

// Pool size is the number of nodes used for group find/set RPC calls
var PoolSize = 6

// K is the maximum number of requests to perform before returning failure.
var KValue = 20

// Alpha is the concurrency factor for asynchronous requests.
var AlphaValue = 3

type DHT struct {
	act  *account.Account // keypair for this dht node
	self peer.ID          // generated by account's public key

	bucketSize   int
	routingTable *kb.RoutingTable // Array of routing tables for differently distanced nodes

	AutoRefresh           bool
	RtRefreshQueryTimeout time.Duration
	RtRefreshPeriod       time.Duration
}

// RoutingTable return dht's routingTable
func (dht *DHT) RoutingTable() *kb.RoutingTable {
	return dht.routingTable
}

// New creates a new DHT with the specified host and options.
func New(ctx context.Context) (*DHT, error) {
	dht := makeDHT(ctx, KValue)
	dht.RtRefreshPeriod = 10 * time.Second
	dht.RtRefreshQueryTimeout = 10 * time.Second

	return dht, nil
}

func makeDHT(ctx context.Context, bucketSize int) *DHT {
	act := peer.MkDHTKeyPair("")
	self := peer.IDFromPublicKey(act.PublicKey)
	rt := kb.NewRoutingTable(bucketSize, kb.ConvertPeerID(self))

	rt.PeerAdded = func(p peer.ID) {
		log.Debugf("dht: peer: %s %d added to dht", p.Pretty(), p.LegacyID)
	}

	rt.PeerRemoved = func(p peer.ID) {
		log.Debugf("dht: peer: %s %d removed from dht", p.Pretty(), p.LegacyID)
	}

	dht := &DHT{
		act:          act,
		self:         self,
		routingTable: rt,
		bucketSize:   bucketSize,

		AutoRefresh: true,
	}

	return dht
}

// Update signals the routingTable to Update its last-seen status
// on the given peer.
func (dht *DHT) Update(peer peer.ID) bool {
	err := dht.routingTable.Update(peer)

	return err == nil
}

func (dht *DHT) Remove(peer peer.ID) {
	dht.routingTable.Remove(peer)
}

func (dht *DHT) BetterPeers(id peer.ID, count int) []peer.ID {
	closer := dht.routingTable.NearestPeers(kb.ConvertPeerID(id), count)
	filtered := make([]peer.ID, 0, len(closer))
	// don't include self and target id
	for _, curID := range closer {
		if curID == dht.self {
			continue
		}
		if curID == id {
			continue
		}
		filtered = append(filtered, curID)
	}

	return filtered
}
