name: Go

# new tag event
on:
  push:
    tags:
      # - '*'
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    # test done
    # - name: command
    #   run: bash ./.travis.script.bash

    - name: command
      run: bash ./.travis.deploy.bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

    - name: Release with attachment
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ontology-linux-amd64
          tool-linux.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: macos-latest
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: command
      run: bash ./.travis.deploy.bash

    - name: Release with attachment
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ontology-darwin-amd64
          tool-darwin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
